version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log/flashCardCreator.log
    maxBytes: 10240000
    backupCount: 3
root:
  level: DEBUG
  handlers: [console,file]
disable_existing_loggers: False
